[0m18:01:41.912525 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9543347ca0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f954210bf10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f954210beb0>]}


============================== 18:01:41.915885 | 35978cf3-7e32-4abe-b7e5-0bfab5063e45 ==============================
[0m18:01:41.915885 [info ] [MainThread]: Running with dbt=1.9.1
[0m18:01:41.916623 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/ibnufajar/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt test', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m18:01:41.917322 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/ibnufajar/ELT-PROJECT/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:01:41.918383 [debug] [MainThread]: Resource report: {"command_name": "test", "command_success": false, "command_wall_clock_time": 0.08026829, "process_in_blocks": "0", "process_kernel_time": 0.068161, "process_mem_max_rss": "85812", "process_out_blocks": "8", "process_user_time": 1.441122}
[0m18:01:41.919022 [debug] [MainThread]: Command `dbt test` failed at 18:01:41.918891 after 0.08 seconds
[0m18:01:41.919479 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9543347ca0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f954210b670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f954210bf10>]}
[0m18:01:41.919980 [debug] [MainThread]: Flushing usage events
[0m18:01:43.211387 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:10:06.342387 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9f204b7cd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9f213ffca0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9f213fffa0>]}


============================== 19:10:06.344700 | 2d91d5f9-c6dc-4b1e-b9f7-7529e642ce75 ==============================
[0m19:10:06.344700 [info ] [MainThread]: Running with dbt=1.9.1
[0m19:10:06.345160 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/home/ibnufajar/.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt docs generate', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m19:10:06.345547 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/ibnufajar/ELT-PROJECT/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:10:06.346172 [debug] [MainThread]: Resource report: {"command_name": "generate", "command_success": false, "command_wall_clock_time": 0.042714804, "process_in_blocks": "0", "process_kernel_time": 0.039057, "process_mem_max_rss": "86116", "process_out_blocks": "16", "process_user_time": 0.761617}
[0m19:10:06.346558 [debug] [MainThread]: Command `dbt docs generate` failed at 19:10:06.346479 after 0.04 seconds
[0m19:10:06.346860 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9f204b7cd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9f213fffa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9f213ffbe0>]}
[0m19:10:06.347150 [debug] [MainThread]: Flushing usage events
[0m19:10:07.392075 [debug] [MainThread]: An error was encountered while trying to flush usage events
